# Generated by Django 4.2.3 on 2024-01-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=25)),
                ("lastname", models.CharField(max_length=25)),
                ("age", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gender", models.CharField(max_length=10)),
                ("email", models.TextField()),
                ("password", models.CharField(max_length=255)),
                ("repassword", models.CharField(max_length=255)),
            ],
        ),
    ]
