# Generated by Django 4.2.3 on 2024-02-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Symptom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="disease",
            name="do_and_dont",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="symptoms",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="treatment",
        ),
        migrations.RemoveField(
            model_name="symptom",
            name="body_part",
        ),
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="symptom",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="BodyPart",
        ),
        migrations.AddField(
            model_name="diseasesymptom",
            name="disease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Symptom.disease"
            ),
        ),
        migrations.AddField(
            model_name="diseasesymptom",
            name="symptom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Symptom.symptom"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="diseasesymptom",
            unique_together={("disease", "symptom")},
        ),
    ]
