# Generated by Django 4.2.3 on 2024-02-17 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Symptom", "0002_diseasesymptom_remove_disease_do_and_dont_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diseasesymptom",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="diseasesymptom",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="diseasesymptom",
            name="symptom",
        ),
        migrations.DeleteModel(
            name="Disease",
        ),
        migrations.DeleteModel(
            name="DiseaseSymptom",
        ),
        migrations.DeleteModel(
            name="Symptom",
        ),
    ]
