# Generated by Django 4.2.3 on 2024-03-06 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Symptom", "0006_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diseasesymptom",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="disease",
            name="name",
        ),
        migrations.RemoveField(
            model_name="symptom",
            name="name",
        ),
        migrations.RemoveField(
            model_name="diseasesymptom",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="diseasesymptom",
            name="symptom",
        ),
    ]
