# Generated by Django 4.2.3 on 2024-03-06 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Symptom", "0007_alter_diseasesymptom_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Disease",
        ),
        migrations.DeleteModel(
            name="DiseaseSymptom",
        ),
        migrations.DeleteModel(
            name="Symptom",
        ),
    ]
