# Generated by Django 4.2.3 on 2024-03-08 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Symptom", "0009_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiseaseSymptom",
        ),
    ]
