# Generated by Django 4.2.3 on 2024-03-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Symptom", "0010_delete_diseasesymptom"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Symptom.disease",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Symptom.symptom",
                    ),
                ),
            ],
            options={
                "unique_together": {("disease", "symptom")},
            },
        ),
    ]
