# Generated by Django 4.2.3 on 2024-03-18 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("age18two65years", "0003_medicine_medicinedisease"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diseasesymptom",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="diseasesymptom",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="diseasesymptom",
            name="symptom",
        ),
        migrations.AlterUniqueTogether(
            name="medicinedisease",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="medicinedisease",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="medicinedisease",
            name="medicine",
        ),
        migrations.DeleteModel(
            name="Disease",
        ),
        migrations.DeleteModel(
            name="DiseaseSymptom",
        ),
        migrations.DeleteModel(
            name="Medicine",
        ),
        migrations.DeleteModel(
            name="MedicineDisease",
        ),
        migrations.DeleteModel(
            name="Symptom",
        ),
    ]
