medicine_names = ['Salicylic acid', 'Topical retinoids', 'Azelaic acid', 'Oral antibiotics', 'Loratadine', 'Cetirizine', 'Fexofenadine', 'Diphenhydramine', 'Fluticasone nasal spray', 'Ferrous sulfate', 'Iron dextran', 'Vitamin B12', 'Epoetin alfa', 'Sertraline', 'Escitalopram', 'Buspirone', 'Venlafaxine', 'Paroxetine', 'Albuterol', 'Fluticasone', 'Montelukast', 'Budesonide', 'Prednisone', 'Ibuprofen', 'Acetaminophen', 'Naproxen', 'Muscle relaxants', 'Gabapentin', 'Azithromycin', 'Amoxicillin', 'Doxycycline', 'Levofloxacin', 'Cefuroxime', 'Paclitaxel', 'Cisplatin', 'Imatinib', 'Trastuzumab', 'Rituximab', 'Gluten-free diet', 'Digestive enzymes', 'Folic acid', 'Vitamin D', 'Calcium supplements', 'Modafinil', 'Pregabalin', 'Selective serotonin reuptake inhibitors (SSRIs)', 'Cognitive behavioral therapy (CBT)', 'Graded exercise therapy (GET)', 'Tiotropium', 'Salmeterol', 'Ipratropium', 'Pseudoephedrine', 'Guaifenesin', 'Dextromethorphan', 'Metformin', 'Insulin', 'Sitagliptin', 'Gliclazide', 'Empagliflozin', 'Duloxetine', 'Milnacipran', 'Amitriptyline', 'Omeprazole', 'Esomeprazole', 'Ranitidine', 'Famotidine', 'Pantoprazole', 'Aspirin', 'Atorvastatin', 'Metoprolol', 'Enalapril', 'Lisinopril', 'Amlodipine', 'Hydrochlorothiazide', 'Losartan', 'Atenolol', 'Mesalamine', 'Azathioprine', 'Infliximab', 'Adalimumab', 'Dicyclomine', 'Loperamide', 'Alosetron', 'Rifaximin', 'Psyllium', 'Furosemide', 'Calcitriol', 'Hydroxychloroquine', 'Mycophenolate mofetil', 'Belimumab', 'Cyclophosphamide', 'Sumatriptan', 'Propranolol', 'Topiramate', 'Valproate', 'Interferon beta-1a', 'Glatiramer acetate', 'Dimethyl fumarate', 'Fingolimod', 'Natalizumab', 'Orlistat', 'Phentermine-topiramate', 'Liraglutide', 'Bupropion-naltrexone', 'Semaglutide', 'Celecoxib', 'Intra-articular corticosteroids', 'Alendronate', 'Risedronate', 'Ibandronate', 'Zoledronic acid', 'Denosumab', 'Levodopa-carbidopa', 'Ropinirole', 'Pramipexole', 'Entacapone', 'Selegiline', 'Methotrexate', 'Leflunomide', 'Sulfasalazine', 'Risperidone', 'Olanzapine', 'Quetiapine', 'Aripiprazole', 'Clozapine', 'Tissue plasminogen activator (tPA)', 'Clopidogrel', 'Ticagrelor', 'Warfarin']
# medicine = []
count = 0
for name in medicine_names:
    count = count + 1
    # if name not in medicine:
    #     medicine.append(name)
print(count)

